client: client.c DieWithError.c ReadFromSocket.c WriteToSocket.c MD5.c CheckMD5.c PrintBlock.c WriteBlock.c PrintList.c BlockList.c CreateSocket.c Put.c Get.c
	gcc -o client client.c DieWithError.c ReadFromSocket.c WriteToSocket.c MD5.c CheckMD5.c PrintBlock.c WriteBlock.c PrintList.c BlockList.c CreateSocket.c Put.c Get.c -lm -lssl -lcrypto
