dr:dr.c AcceptDRTCPConnection.c CreateDRTCPServerSocket.c DieWithError.c HandleDRTCPClient.c ReadFromSocket.c WriteToSocket.c MD5.c RemoveFile.c RemoveAuthFolder.c PrintBlock.c CheckMD5.c CountFiles.c CreateFolder.c CheckNewFile.c CheckNewUser.c WriteToFile.c WriteBlock.c Get.c
	gcc -o dr dr.c AcceptDRTCPConnection.c CreateDRTCPServerSocket.c DieWithError.c HandleDRTCPClient.c ReadFromSocket.c WriteToSocket.c MD5.c RemoveFile.c RemoveAuthFolder.c PrintBlock.c CheckMD5.c CountFiles.c CreateFolder.c CheckNewFile.c CheckNewUser.c WriteToFile.c WriteBlock.c Get.c -lcrypto -lssl

